package com.fashionplace.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * A record of a key action a user performed (e.g. placing an order or changing a
 * product), captured by {@code ActivityLogInterceptor} and shown in the admin area.
 *
 * <p>This is an audit trail rather than a domain relationship, so the actor is stored
 * as a plain {@code username} string instead of a {@code @ManyToOne User}: the entry
 * must survive even if the user is later removed.</p>
 */
@Entity
public class ActivityLog {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Username of the actor at the time of the action (or {@code anonymous}). */
    @Column(nullable = false)
    private String username;

    /** Human-friendly description of the action, e.g. {@code "Placed order"}. */
    @Column(nullable = false)
    private String action;

    /** HTTP method of the request that triggered the action. */
    private String method;

    /** Request path that triggered the action. */
    private String path;

    /** When the action happened, set automatically on first persist. */
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    /** No-args constructor required by JPA. */
    public ActivityLog() {
    }

    /**
     * Creates an activity log entry; {@code createdAt} is set automatically on persist.
     *
     * @param username the actor's username (or {@code anonymous})
     * @param action   the human-friendly action description
     * @param method   the HTTP method
     * @param path     the request path
     */
    public ActivityLog(String username, String action, String method, String path) {
        this.username = username;
        this.action = action;
        this.method = method;
        this.path = path;
    }

    /** @return the entry id, or {@code null} if not yet persisted */
    public Long getId() {
        return id;
    }

    /** @param id the entry id */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the actor's username */
    public String getUsername() {
        return username;
    }

    /** @param username the actor's username */
    public void setUsername(String username) {
        this.username = username;
    }

    /** @return the action description */
    public String getAction() {
        return action;
    }

    /** @param action the action description */
    public void setAction(String action) {
        this.action = action;
    }

    /** @return the HTTP method */
    public String getMethod() {
        return method;
    }

    /** @param method the HTTP method */
    public void setMethod(String method) {
        this.method = method;
    }

    /** @return the request path */
    public String getPath() {
        return path;
    }

    /** @param path the request path */
    public void setPath(String path) {
        this.path = path;
    }

    /** @return when the action happened */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** @param createdAt the creation timestamp */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
