package com.fashionplace.model;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * A placed order: a snapshot of what a buyer purchased in one checkout.
 *
 * <p>Mapped to the {@code orders} table because {@code ORDER} is a reserved SQL word.
 * Links to one {@link User} (buyer) and owns its {@link OrderItem} lines.</p>
 */
@Entity
@Table(name = "orders")
public class Order {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Grand total charged for the whole order. */
    @Column(nullable = false)
    private BigDecimal totalPrice;

    /** Order state, e.g. {@code PLACED}, {@code SHIPPED}, {@code CANCELLED}. */
    @Column(nullable = false)
    private String status;

    /** Where the order ships to (captured at checkout). */
    private String shippingAddress;

    /** The buyer who placed the order. */
    @ManyToOne
    @JoinColumn(name = "buyer_id", nullable = false)
    private User buyer;

    /**
     * The line items in this order. The {@link OrderItem} side owns the foreign key
     * ({@code mappedBy = "order"}); cascading persists/removes lines together with the order.
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<OrderItem> orderItems = new ArrayList<>();

    /** Creation time, set automatically on first persist. */
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    /** No-args constructor required by JPA. */
    public Order() {
    }

    /**
     * Creates an order; {@code createdAt} is set automatically on persist.
     *
     * @param buyer           the purchasing user
     * @param totalPrice      the grand total
     * @param status          the initial status
     * @param shippingAddress the delivery address
     */
    public Order(User buyer, BigDecimal totalPrice, String status, String shippingAddress) {
        this.buyer = buyer;
        this.totalPrice = totalPrice;
        this.status = status;
        this.shippingAddress = shippingAddress;
    }

    /**
     * Adds a line to this order and back-links it, keeping both sides consistent.
     *
     * @param item the line item to add
     */
    public void addItem(OrderItem item) {
        item.setOrder(this);
        orderItems.add(item);
    }

    /** @return the order id, or {@code null} if not yet persisted */
    public Long getId() {
        return id;
    }

    /** @param id the order id */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the grand total */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /** @param totalPrice the grand total */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /** @return the order status */
    public String getStatus() {
        return status;
    }

    /** @param status the order status */
    public void setStatus(String status) {
        this.status = status;
    }

    /** @return the shipping address */
    public String getShippingAddress() {
        return shippingAddress;
    }

    /** @param shippingAddress the shipping address */
    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    /** @return the buyer */
    public User getBuyer() {
        return buyer;
    }

    /** @param buyer the buyer */
    public void setBuyer(User buyer) {
        this.buyer = buyer;
    }

    /** @return the order's line items */
    public List<OrderItem> getOrderItems() {
        return orderItems;
    }

    /** @param orderItems the order's line items */
    public void setOrderItems(List<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }

    /** @return when this order was created */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** @param createdAt the creation timestamp */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
