package com.fashionplace.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

import java.math.BigDecimal;

/**
 * A single line within an {@link Order}: one product, a quantity, and the price paid.
 *
 * <p>{@code priceAtPurchase} records the product price at checkout time so later price
 * changes do not alter historical orders. Links to its parent {@link Order} and the
 * purchased {@link Product} via {@code order_id} and {@code product_id} foreign keys.</p>
 */
@Entity
public class OrderItem {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Number of units purchased. */
    @Column(nullable = false)
    private int quantity;

    /** Unit price captured at purchase time (immune to later product price changes). */
    @Column(nullable = false)
    private BigDecimal priceAtPurchase;

    /** The order this line belongs to. */
    @ManyToOne
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    /** The purchased product. */
    @ManyToOne
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** No-args constructor required by JPA. */
    public OrderItem() {
    }

    /**
     * Creates a line item. The parent order is set when added via {@link Order#addItem}.
     *
     * @param product         the purchased product
     * @param quantity        the number of units
     * @param priceAtPurchase the unit price at purchase time
     */
    public OrderItem(Product product, int quantity, BigDecimal priceAtPurchase) {
        this.product = product;
        this.quantity = quantity;
        this.priceAtPurchase = priceAtPurchase;
    }

    /** @return the line item id, or {@code null} if not yet persisted */
    public Long getId() {
        return id;
    }

    /** @param id the line item id */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the quantity purchased */
    public int getQuantity() {
        return quantity;
    }

    /** @param quantity the quantity purchased */
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    /** @return the unit price at purchase time */
    public BigDecimal getPriceAtPurchase() {
        return priceAtPurchase;
    }

    /** @param priceAtPurchase the unit price at purchase time */
    public void setPriceAtPurchase(BigDecimal priceAtPurchase) {
        this.priceAtPurchase = priceAtPurchase;
    }

    /** @return the parent order */
    public Order getOrder() {
        return order;
    }

    /** @param order the parent order */
    public void setOrder(Order order) {
        this.order = order;
    }

    /** @return the purchased product */
    public Product getProduct() {
        return product;
    }

    /** @param product the purchased product */
    public void setProduct(Product product) {
        this.product = product;
    }

    /**
     * Convenience total for this line.
     *
     * @return {@code priceAtPurchase * quantity}
     */
    public BigDecimal getLineTotal() {
        return priceAtPurchase.multiply(BigDecimal.valueOf(quantity));
    }
}
