package com.fashionplace.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.math.BigDecimal;

/**
 * A product offered for sale on the FashionPlace marketplace (jewelry or clothing).
 *
 * <p>This is the first persistent entity of the application. It is mapped to a database
 * table by JPA/Hibernate; with {@code spring.jpa.hibernate.ddl-auto=update} configured,
 * Hibernate creates (or updates) the {@code product} table automatically at startup.</p>
 *
 * <p>Beyond the core fields ({@code id}, {@code title}, {@code description}, {@code price}),
 * Phase 2.2 adds {@code category}, {@code condition}, {@code status} and {@code imageUrl}
 * to support browsing filters and listing state. The seller relation is added in a later phase.</p>
 */
@Entity
public class Product {

    /**
     * Primary key, generated by the database.
     *
     * <p>{@link GenerationType#IDENTITY} delegates id generation to the database's
     * auto-increment column, which matches MariaDB's behaviour.</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Short, human-readable name of the product shown on cards and the detail page. */
    private String title;

    /** Longer free-text description of the product. */
    private String description;

    /** Selling price. {@link BigDecimal} is used to avoid floating-point rounding errors on money. */
    private BigDecimal price;

    /** High-level grouping used for browsing/filtering (e.g. "Jewelry", "Clothing"). */
    private String category;

    /**
     * Physical condition of the item (e.g. "New", "Used"). Mapped to {@code item_condition}
     * because {@code condition} is a reserved word in SQL.
     */
    @Column(name = "item_condition")
    private String condition;

    /** Listing state, e.g. {@code ACTIVE} or {@code SOLD}. Defaults to {@code ACTIVE}. */
    private String status = "ACTIVE";

    /** Optional URL of the product image shown on cards and the detail page. */
    private String imageUrl;

    /**
     * No-args constructor required by JPA to instantiate entities via reflection.
     */
    public Product() {
    }

    /**
     * Convenience constructor for the core fields. {@code status} defaults to {@code ACTIVE}.
     *
     * @param title       the product title
     * @param description the product description
     * @param price       the selling price
     */
    public Product(String title, String description, BigDecimal price) {
        this.title = title;
        this.description = description;
        this.price = price;
    }

    /**
     * Full convenience constructor for creating a product in code (e.g. seed data).
     *
     * @param title       the product title
     * @param description the product description
     * @param price       the selling price
     * @param category    the product category
     * @param condition   the item condition
     * @param status      the listing status (e.g. {@code ACTIVE}, {@code SOLD})
     * @param imageUrl    the product image URL
     */
    public Product(String title, String description, BigDecimal price,
                   String category, String condition, String status, String imageUrl) {
        this.title = title;
        this.description = description;
        this.price = price;
        this.category = category;
        this.condition = condition;
        this.status = status;
        this.imageUrl = imageUrl;
    }

    /**
     * Returns the database-generated identifier, or {@code null} if not yet persisted.
     *
     * @return the product id
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the identifier. Normally managed by JPA; rarely set manually.
     *
     * @param id the product id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the product title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the product title.
     *
     * @param title the title to set
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the product description.
     *
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the product description.
     *
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the selling price.
     *
     * @return the price
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the selling price.
     *
     * @param price the price to set
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Returns the product category.
     *
     * @return the category
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the product category.
     *
     * @param category the category to set
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Returns the item condition.
     *
     * @return the condition
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the item condition.
     *
     * @param condition the condition to set
     */
    public void setCondition(String condition) {
        this.condition = condition;
    }

    /**
     * Returns the listing status.
     *
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the listing status.
     *
     * @param status the status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Returns the product image URL.
     *
     * @return the image URL
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * Sets the product image URL.
     *
     * @param imageUrl the image URL to set
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
}
