package com.fashionplace.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.math.BigDecimal;

/**
 * A product offered for sale on the FashionPlace marketplace (jewelry or clothing).
 *
 * <p>This is the first persistent entity of the application. It is mapped to a database
 * table by JPA/Hibernate; with {@code spring.jpa.hibernate.ddl-auto=update} configured,
 * Hibernate creates (or updates) the {@code product} table automatically at startup.</p>
 *
 * <p>This is the minimal version (Phase 1.1): it holds only the essential fields
 * ({@code id}, {@code title}, {@code description}, {@code price}). Additional fields such
 * as category, condition, status, image and the seller relation are introduced in later phases.</p>
 */
@Entity
public class Product {

    /**
     * Primary key, generated by the database.
     *
     * <p>{@link GenerationType#IDENTITY} delegates id generation to the database's
     * auto-increment column, which matches MariaDB's behaviour.</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Short, human-readable name of the product shown on cards and the detail page. */
    private String title;

    /** Longer free-text description of the product. */
    private String description;

    /** Selling price. {@link BigDecimal} is used to avoid floating-point rounding errors on money. */
    private BigDecimal price;

    /**
     * No-args constructor required by JPA to instantiate entities via reflection.
     */
    public Product() {
    }

    /**
     * Convenience constructor for creating a product in code (e.g. seed data).
     *
     * @param title       the product title
     * @param description the product description
     * @param price       the selling price
     */
    public Product(String title, String description, BigDecimal price) {
        this.title = title;
        this.description = description;
        this.price = price;
    }

    /**
     * Returns the database-generated identifier, or {@code null} if not yet persisted.
     *
     * @return the product id
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the identifier. Normally managed by JPA; rarely set manually.
     *
     * @param id the product id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the product title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the product title.
     *
     * @param title the title to set
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the product description.
     *
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the product description.
     *
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the selling price.
     *
     * @return the price
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the selling price.
     *
     * @param price the price to set
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}
