package com.fashionplace.model;

import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;

import java.math.BigDecimal;

/**
 * A product offered for sale on the FashionPlace marketplace (jewelry or clothing).
 *
 * <p>This is the first persistent entity of the application. It is mapped to a database
 * table by JPA/Hibernate; with {@code spring.jpa.hibernate.ddl-auto=update} configured,
 * Hibernate creates (or updates) the {@code product} table automatically at startup.</p>
 *
 * <p>Beyond the core fields ({@code id}, {@code title}, {@code description}, {@code price}),
 * Phase 2.2 adds {@code category}, {@code condition}, {@code status} and {@code imageUrl},
 * and Phase 4.3 adds a {@code seller} relation pointing to the {@link User} who listed it.</p>
 */
@Entity
public class Product {

    /**
     * Primary key, generated by the database.
     *
     * <p>{@link GenerationType#IDENTITY} delegates id generation to the database's
     * auto-increment column, which matches MariaDB's behaviour.</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Short, human-readable name of the product shown on cards and the detail page. */
    private String title;

    /** Longer free-text description of the product. */
    private String description;

    /** Selling price. {@link BigDecimal} is used to avoid floating-point rounding errors on money. */
    private BigDecimal price;

    /** High-level grouping used for browsing/filtering (e.g. "Jewelry", "Clothing"). */
    private String category;

    /**
     * Physical condition of the item (e.g. "New", "Used"). Mapped to {@code item_condition}
     * because {@code condition} is a reserved word in SQL.
     */
    @Column(name = "item_condition")
    private String condition;

    /** Listing state, e.g. {@code ACTIVE} or {@code SOLD}. Defaults to {@code ACTIVE}. */
    private String status = "ACTIVE";

    /**
     * Soft-delete flag. A deleted product is hidden from Browse, search, recommendations,
     * the wishlist, and the seller's My Products page, but is kept in the database so that
     * past orders can still display the purchased item and its details.
     */
    @Column(nullable = false)
    private boolean deleted = false;

    /** Units currently in stock. Becomes {@code SOLD} once this reaches zero. */
    @Column(nullable = false)
    private int quantity = 1;

    /** Optional URL of the product image shown on cards and the detail page (e.g. seed data). */
    private String imageUrl;

    /**
     * Raw bytes of an uploaded image, stored directly in the database as a BLOB.
     *
     * <p>Marked {@link FetchType#LAZY} so list/browse queries don't pull the binary
     * payload unless the image is actually requested. {@link #imageContentType} stays
     * eagerly loaded so views can tell whether an upload exists without reading the blob.</p>
     */
    @Lob
    @Basic(fetch = FetchType.LAZY)
    @Column(name = "image_data", columnDefinition = "LONGBLOB")
    private byte[] imageData;

    /** MIME type of the uploaded {@link #imageData} (e.g. {@code image/png}); {@code null} if none. */
    @Column(name = "image_content_type")
    private String imageContentType;

    /**
     * The user who listed this product. Many products can belong to one seller;
     * JPA maps this to a {@code seller_id} foreign key column.
     */
    @ManyToOne
    @JoinColumn(name = "seller_id")
    private User seller;

    /**
     * No-args constructor required by JPA to instantiate entities via reflection.
     */
    public Product() {
    }

    /**
     * Convenience constructor for the core fields. {@code status} defaults to {@code ACTIVE}.
     *
     * @param title       the product title
     * @param description the product description
     * @param price       the selling price
     */
    public Product(String title, String description, BigDecimal price) {
        this.title = title;
        this.description = description;
        this.price = price;
    }

    /**
     * Full convenience constructor for creating a product in code (e.g. seed data).
     *
     * @param title       the product title
     * @param description the product description
     * @param price       the selling price
     * @param category    the product category
     * @param condition   the item condition
     * @param status      the listing status (e.g. {@code ACTIVE}, {@code SOLD})
     * @param quantity    the units in stock
     * @param imageUrl    the product image URL
     */
    public Product(String title, String description, BigDecimal price,
                   String category, String condition, String status, int quantity, String imageUrl) {
        this.title = title;
        this.description = description;
        this.price = price;
        this.category = category;
        this.condition = condition;
        this.status = status;
        this.quantity = quantity;
        this.imageUrl = imageUrl;
    }

    /**
     * Returns the database-generated identifier, or {@code null} if not yet persisted.
     *
     * @return the product id
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the identifier. Normally managed by JPA; rarely set manually.
     *
     * @param id the product id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the product title.
     *
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the product title.
     *
     * @param title the title to set
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the product description.
     *
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the product description.
     *
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the selling price.
     *
     * @return the price
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the selling price.
     *
     * @param price the price to set
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Returns the product category.
     *
     * @return the category
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the product category.
     *
     * @param category the category to set
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Returns the item condition.
     *
     * @return the condition
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the item condition.
     *
     * @param condition the condition to set
     */
    public void setCondition(String condition) {
        this.condition = condition;
    }

    /**
     * Returns the listing status.
     *
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the listing status.
     *
     * @param status the status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Whether this product has been soft-deleted (hidden everywhere except order history).
     *
     * @return {@code true} if deleted
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the soft-delete flag.
     *
     * @param deleted whether the product is deleted
     */
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * Returns the units currently in stock.
     *
     * @return the quantity
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the units currently in stock.
     *
     * @param quantity the quantity to set
     */
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    /**
     * Returns the product image URL.
     *
     * @return the image URL
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * Sets the product image URL.
     *
     * @param imageUrl the image URL to set
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * Returns the raw bytes of the uploaded image, or {@code null} if none was uploaded.
     *
     * @return the image data
     */
    public byte[] getImageData() {
        return imageData;
    }

    /**
     * Sets the raw bytes of the uploaded image.
     *
     * @param imageData the image data to set
     */
    public void setImageData(byte[] imageData) {
        this.imageData = imageData;
    }

    /**
     * Returns the MIME type of the uploaded image, or {@code null} if none was uploaded.
     *
     * @return the image content type
     */
    public String getImageContentType() {
        return imageContentType;
    }

    /**
     * Sets the MIME type of the uploaded image.
     *
     * @param imageContentType the content type to set
     */
    public void setImageContentType(String imageContentType) {
        this.imageContentType = imageContentType;
    }

    /**
     * Whether this product has an uploaded image stored in the database (as opposed to
     * an external {@link #imageUrl}). Checks the cheap content-type column, not the blob.
     *
     * @return {@code true} if an uploaded image is available
     */
    public boolean isHasUploadedImage() {
        return imageContentType != null;
    }

    /**
     * Returns the seller who listed this product.
     *
     * @return the seller, possibly {@code null}
     */
    public User getSeller() {
        return seller;
    }

    /**
     * Sets the seller who listed this product.
     *
     * @param seller the seller to set
     */
    public void setSeller(User seller) {
        this.seller = seller;
    }
}
