package com.fashionplace.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * A product review left by a user (rating 1–5 and a comment).
 *
 * <p>Each review links to one {@link User} (reviewer) and one {@link Product}.
 * JPA maps these to {@code reviewer_id} and {@code product_id} foreign keys.</p>
 */
@Entity
public class Review {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Star rating from 1 (worst) to 5 (best). */
    @Column(nullable = false)
    private int rating;

    /** Free-text review comment. */
    @Column(nullable = false, length = 2000)
    private String comment;

    /** The user who wrote the review. */
    @ManyToOne
    @JoinColumn(name = "reviewer_id", nullable = false)
    private User reviewer;

    /** The product being reviewed. */
    @ManyToOne
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** Creation time, set automatically on first persist. */
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    /** No-args constructor required by JPA. */
    public Review() {
    }

    /**
     * Creates a review; {@code createdAt} is set automatically on persist.
     *
     * @param rating   star rating (1–5)
     * @param comment  the review text
     * @param reviewer the user who wrote it
     * @param product  the product being reviewed
     */
    public Review(int rating, String comment, User reviewer, Product product) {
        this.rating = rating;
        this.comment = comment;
        this.reviewer = reviewer;
        this.product = product;
    }

    /** @return the review id, or {@code null} if not yet persisted */
    public Long getId() {
        return id;
    }

    /** @param id the review id */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the star rating (1–5) */
    public int getRating() {
        return rating;
    }

    /** @param rating the star rating (1–5) */
    public void setRating(int rating) {
        this.rating = rating;
    }

    /** @return the review comment */
    public String getComment() {
        return comment;
    }

    /** @param comment the review comment */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /** @return the reviewer */
    public User getReviewer() {
        return reviewer;
    }

    /** @param reviewer the reviewer */
    public void setReviewer(User reviewer) {
        this.reviewer = reviewer;
    }

    /** @return the reviewed product */
    public Product getProduct() {
        return product;
    }

    /** @param product the reviewed product */
    public void setProduct(Product product) {
        this.product = product;
    }

    /** @return when this review was created */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** @param createdAt the creation timestamp */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
