package com.fashionplace.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * One message in a customer-support conversation between a {@link User} and the support team.
 *
 * <p>A conversation is a sequence of {@code SupportMessage} rows that share the same
 * {@code user} and {@code subject}: the user's opening message plus any replies. Each row
 * records who sent it via {@link #senderType} ({@code USER} or {@code SUPPORT}). The
 * {@link #status} ({@code OPEN} or {@code CLOSED}) reflects the state of the conversation.</p>
 *
 * <p>Following the existing codebase convention (see {@link Product} and {@link Order}),
 * {@code senderType} and {@code status} are stored as plain strings rather than enums.</p>
 */
@Entity
public class SupportMessage {

    /** Sender type for a message the user wrote. */
    public static final String SENDER_USER = "USER";

    /** Sender type for a message the support team wrote. */
    public static final String SENDER_SUPPORT = "SUPPORT";

    /** Status of an unresolved conversation. */
    public static final String STATUS_OPEN = "OPEN";

    /** Status of a resolved conversation. */
    public static final String STATUS_CLOSED = "CLOSED";

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Short subject line that ties a conversation together. */
    @Column(nullable = false)
    private String subject;

    /** The message text. */
    @Lob
    @Column(nullable = false)
    private String body;

    /** Who sent this message: {@code USER} or {@code SUPPORT}. */
    @Column(nullable = false)
    private String senderType;

    /** Conversation state: {@code OPEN} or {@code CLOSED}. */
    @Column(nullable = false)
    private String status = STATUS_OPEN;

    /** The user this conversation belongs to (the customer, not the support agent). */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Creation time, set automatically on first persist. */
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    /** No-args constructor required by JPA. */
    public SupportMessage() {
    }

    /**
     * Creates a support message; {@code createdAt} is set automatically on persist.
     *
     * @param user       the customer the conversation belongs to
     * @param subject    the conversation subject
     * @param body       the message text
     * @param senderType who sent it ({@code USER} or {@code SUPPORT})
     * @param status     the conversation state ({@code OPEN} or {@code CLOSED})
     */
    public SupportMessage(User user, String subject, String body, String senderType, String status) {
        this.user = user;
        this.subject = subject;
        this.body = body;
        this.senderType = senderType;
        this.status = status;
    }

    /** @return the message id, or {@code null} if not yet persisted */
    public Long getId() {
        return id;
    }

    /** @param id the message id */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the subject line */
    public String getSubject() {
        return subject;
    }

    /** @param subject the subject line */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /** @return the message text */
    public String getBody() {
        return body;
    }

    /** @param body the message text */
    public void setBody(String body) {
        this.body = body;
    }

    /** @return who sent the message ({@code USER} or {@code SUPPORT}) */
    public String getSenderType() {
        return senderType;
    }

    /** @param senderType who sent the message */
    public void setSenderType(String senderType) {
        this.senderType = senderType;
    }

    /** @return the conversation status ({@code OPEN} or {@code CLOSED}) */
    public String getStatus() {
        return status;
    }

    /** @param status the conversation status */
    public void setStatus(String status) {
        this.status = status;
    }

    /** @return the customer this conversation belongs to */
    public User getUser() {
        return user;
    }

    /** @param user the customer this conversation belongs to */
    public void setUser(User user) {
        this.user = user;
    }

    /** @return when this message was created */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** @param createdAt the creation timestamp */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
