package com.fashionplace.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * A registered account (admin, seller or buyer).
 *
 * <p>Mapped to {@code app_user} because {@code USER} is a reserved SQL word.
 * {@code passwordHash} stores a BCrypt hash (never plain text).</p>
 */
@Entity
@Table(name = "app_user")
public class User {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique login name. */
    @Column(nullable = false, unique = true)
    private String username;

    /** Unique contact email. */
    @Column(nullable = false, unique = true)
    private String email;

    /** BCrypt-hashed password. */
    @Column(nullable = false)
    private String passwordHash;

    /** Authorization role, e.g. {@code ADMIN} or {@code USER}. */
    @Column(nullable = false)
    private String role;

    /** Optional postal/shipping address. */
    private String address;

    /**
     * Whether an admin has disabled this account. Stored as a flag (rather than an
     * {@code enabled} column) so that adding it to an existing database leaves current
     * rows {@code false} — i.e. still enabled. A disabled user is treated as blocked.
     */
    @Column(nullable = false)
    private boolean disabled = false;

    /** Creation time, set automatically on first persist. */
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    /** No-args constructor required by JPA. */
    public User() {
    }

    /**
     * Creates a user (e.g. seed data); {@code createdAt} is set automatically.
     *
     * @param username     the unique login name
     * @param email        the unique contact email
     * @param passwordHash the hashed password
     * @param role         the authorization role
     * @param address      the address (may be {@code null})
     */
    public User(String username, String email, String passwordHash, String role, String address) {
        this.username = username;
        this.email = email;
        this.passwordHash = passwordHash;
        this.role = role;
        this.address = address;
    }

    /** @return the user id, or {@code null} if not yet persisted */
    public Long getId() {
        return id;
    }

    /** @param id the user id */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the username */
    public String getUsername() {
        return username;
    }

    /** @param username the username to set */
    public void setUsername(String username) {
        this.username = username;
    }

    /** @return the email */
    public String getEmail() {
        return email;
    }

    /** @param email the email to set */
    public void setEmail(String email) {
        this.email = email;
    }

    /** @return the password hash */
    public String getPasswordHash() {
        return passwordHash;
    }

    /** @param passwordHash the password hash to set (never plain text) */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /** @return the role */
    public String getRole() {
        return role;
    }

    /** @param role the role to set */
    public void setRole(String role) {
        this.role = role;
    }

    /** @return the address, possibly {@code null} */
    public String getAddress() {
        return address;
    }

    /** @param address the address to set */
    public void setAddress(String address) {
        this.address = address;
    }

    /** @return {@code true} if this account has been disabled by an admin */
    public boolean isDisabled() {
        return disabled;
    }

    /** @param disabled whether the account is disabled */
    public void setDisabled(boolean disabled) {
        this.disabled = disabled;
    }

    /** @return when this account was created */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** @param createdAt the creation timestamp to set */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
