package com.fashionplace.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * A product saved to a user's wishlist.
 *
 * <p>Each item links one {@link User} (owner) to one {@link Product}. JPA maps these
 * to {@code owner_id} and {@code product_id} foreign keys.</p>
 */
@Entity
@Table(uniqueConstraints = @UniqueConstraint(columnNames = {"owner_id", "product_id"}))
public class WishlistItem {

    /** Primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The user who saved the product. */
    @ManyToOne
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;

    /** The saved product. */
    @ManyToOne
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** Creation time, set automatically on first persist. */
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    /** No-args constructor required by JPA. */
    public WishlistItem() {
    }

    /**
     * Creates a wishlist item; {@code createdAt} is set automatically on persist.
     *
     * @param owner   the user saving the product
     * @param product the saved product
     */
    public WishlistItem(User owner, Product product) {
        this.owner = owner;
        this.product = product;
    }

    /** @return the wishlist item id, or {@code null} if not yet persisted */
    public Long getId() {
        return id;
    }

    /** @param id the wishlist item id */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the owner */
    public User getOwner() {
        return owner;
    }

    /** @param owner the owner */
    public void setOwner(User owner) {
        this.owner = owner;
    }

    /** @return the saved product */
    public Product getProduct() {
        return product;
    }

    /** @param product the saved product */
    public void setProduct(Product product) {
        this.product = product;
    }

    /** @return when this item was saved */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** @param createdAt the creation timestamp */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
